# Set theme
remote_theme: bloodf/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

plugins:
- jekyll-remote-theme

# Site settings
url: 'https://vuestorefront.github.io/brighter_future/'
baseurl: 'https://vuestorefront.github.io/brighter_future/'
title: 'A brighter future'
description: 'Tech Mentorship for the young refugees'
permalink: pretty
logo: ""
