# Set theme
remote_theme: bloodf/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

plugins:
- jekyll-remote-theme

# Site settings
url: 'https://vuestorefront.github.io/brighter_future/'
baseurl: 'https://vuestorefront.github.io/brighter_future/'
title: 'A brighter future'
description: 'Tech Mentorship for the young refugees'
permalink: pretty
logo: ''

sass:
  style: compressed # Style compression
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,400;1,700&display=swap
